#!/usr/bin/env bash
# Display information about subdomains

run_dig ()
{
    a=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -n1)
    echo "$2 $a" |
    awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6 ""}'
}

if [ "$#" == 1 ]
then
    run_dig "$1" "www"
    run_dig "$1" "lb-01"
    run_dig "$1" "web-01"
    run_dig "$1" "web-02"
elif [ "$#" == 2 ]
then
    echo -n "The subdomain $2 is a "
    dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -n1 |
    awk '{print $4 " record and points to " $5}'
fi
