#!/usr/bin/env bash
# This Bash script configures an Ubuntu server with:
#   localhost resolves to 127.0.0.2
#   facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts2.new
echo "8.8.8.8 facebook.com" >> ~/hosts2.new
cp -f ~/hosts2.new /etc/hosts
cat ~/hosts.new >> /etc/hosts
