#!/usr/bin/env bash
# Make task#1 solution short and sweet per requirements
pkill apache2
chmod 777 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
